package testcases.AccountReceivable;

import com.winSupply.core.CoreScript;
import com.winSupply.core.TestConfigurations;
import com.winSupply.framework.selenium.SeleniumTestParameters;
import org.testng.annotations.Test;

public class MiscChargesAndAdjustments extends TestConfigurations {

    @Test(groups = {}, dataProvider = "DesktopBrowsers", dataProviderClass = TestConfigurations.class)
    public void Tc_365_verifyUIMiscChargesAdjustmentsPage(SeleniumTestParameters testParameters) {
        testParameters.setCurrentTestDescription("Test to verify UI of Misc charges and adjustments page");
        CoreScript coreScript = new CoreScript(testParameters);
        coreScript.driveTestExecution();
        tearDownTestRunner(testParameters, coreScript);
    }

    @Test(groups = {}, dataProvider = "DesktopBrowsers", dataProviderClass = TestConfigurations.class)
    public void Tc_371_verifyDisplayEBP(SeleniumTestParameters testParameters) {
        testParameters.setCurrentTestDescription("Test to verify if invoice adjustment is reflected on \"Cash Receipts/Adj Entry\" page for Credit Memo");
        CoreScript coreScript = new CoreScript(testParameters);
        coreScript.driveTestExecution();
        tearDownTestRunner(testParameters, coreScript);
    }

    @Test(groups = {}, dataProvider = "DesktopBrowsers", dataProviderClass = TestConfigurations.class)
    public void Tc_364_verifyInvoiceReflectedOnCashRecAdjEntryCreditMemo(SeleniumTestParameters testParameters) {
        testParameters.setCurrentTestDescription("Test to verify if invoice adjustment is reflected on \"Cash Receipts/Adj Entry\" page for Credit Memo");
        CoreScript coreScript = new CoreScript(testParameters);
        coreScript.driveTestExecution();
        tearDownTestRunner(testParameters, coreScript);
    }

    @Test(groups = {}, dataProvider = "DesktopBrowsers", dataProviderClass = TestConfigurations.class)
    public void Tc_366_verifyInvoiceNoAutoGenerate(SeleniumTestParameters testParameters) {
        testParameters.setCurrentTestDescription("Test to verify if user wants invoice number to auto generate or not for Credit Memo");
        CoreScript coreScript = new CoreScript(testParameters);
        coreScript.driveTestExecution();
        tearDownTestRunner(testParameters, coreScript);
    }

    @Test(groups = {}, dataProvider = "DesktopBrowsers", dataProviderClass = TestConfigurations.class)
    public void Tc_verifyDisplayEBPDebit(SeleniumTestParameters testParameters) {
        testParameters.setCurrentTestDescription("Test to verify if invoice adjustment is reflected on \"Cash Receipts/Adj Entry\" page for Debit Memo");
        CoreScript coreScript = new CoreScript(testParameters);
        coreScript.driveTestExecution();
        tearDownTestRunner(testParameters, coreScript);
    }

    @Test(groups = {}, dataProvider = "DesktopBrowsers", dataProviderClass = TestConfigurations.class)
    public void Tc_changeAutoInvoiceNo(SeleniumTestParameters testParameters) {
        testParameters.setCurrentTestDescription("Test to verify if invoice adjustment is reflected on \"Cash Receipts/Adj Entry\" page for Debit Memo");
        CoreScript coreScript = new CoreScript(testParameters);
        coreScript.driveTestExecution();
        tearDownTestRunner(testParameters, coreScript);
    }

    @Test(groups = {}, dataProvider = "DesktopBrowsers", dataProviderClass = TestConfigurations.class)
    public void Tc_384_verifyInvoiceReflectedOnCashRecAdjEntryDebitMemo(SeleniumTestParameters testParameters) {
        testParameters.setCurrentTestDescription("Test to verify if invoice adjustment is reflected on \"Cash Receipts/Adj Entry\" page for Debit Memo");
        CoreScript coreScript = new CoreScript(testParameters);
        coreScript.driveTestExecution();
        tearDownTestRunner(testParameters, coreScript);
    }

    @Test(groups = {}, dataProvider = "DesktopBrowsers", dataProviderClass = TestConfigurations.class)
    public void Tc_385_verifyInvoiceNoAutoGenerateDebit(SeleniumTestParameters testParameters) {
        testParameters.setCurrentTestDescription("Test to verify if user wants invoice number to auto generate or not for Debit Memo");
        CoreScript coreScript = new CoreScript(testParameters);
        coreScript.driveTestExecution();
        tearDownTestRunner(testParameters, coreScript);
    }

    @Test(groups = {}, dataProvider = "DesktopBrowsers", dataProviderClass = TestConfigurations.class)
    public void Tc_382_verifyActionCodeField(SeleniumTestParameters testParameters) {
        testParameters.setCurrentTestDescription("Field verification for the 'Action code' field");
        CoreScript coreScript = new CoreScript(testParameters);
        coreScript.driveTestExecution();
        tearDownTestRunner(testParameters, coreScript);
    }

    @Test(groups = {}, dataProvider = "DesktopBrowsers", dataProviderClass = TestConfigurations.class)
    public void Tc_383_verifyTransactionTypeField(SeleniumTestParameters testParameters) {
        testParameters.setCurrentTestDescription("Field verification for the 'Transaction type' field");
        CoreScript coreScript = new CoreScript(testParameters);
        coreScript.driveTestExecution();
        tearDownTestRunner(testParameters, coreScript);
    }

    @Test(groups = {}, dataProvider = "DesktopBrowsers", dataProviderClass = TestConfigurations.class)
    public void Tc_388_verifyMemoTypeField(SeleniumTestParameters testParameters) {
        testParameters.setCurrentTestDescription("Field verification for the 'Memo type' field");
        CoreScript coreScript = new CoreScript(testParameters);
        coreScript.driveTestExecution();
        tearDownTestRunner(testParameters, coreScript);
    }

    @Test(groups = {}, dataProvider = "DesktopBrowsers", dataProviderClass = TestConfigurations.class)
    public void Tc_389_verifyAccountNoField(SeleniumTestParameters testParameters) {
        testParameters.setCurrentTestDescription("Field verification for 'Account number'");
        CoreScript coreScript = new CoreScript(testParameters);
        coreScript.driveTestExecution();
        tearDownTestRunner(testParameters, coreScript);
    }

    @Test(groups = {}, dataProvider = "DesktopBrowsers", dataProviderClass = TestConfigurations.class)
    public void Tc_390_verifyInvoiceCommentLines(SeleniumTestParameters testParameters) {
        testParameters.setCurrentTestDescription("Field verification for 'Invoice Comment Lines'");
        CoreScript coreScript = new CoreScript(testParameters);
        coreScript.driveTestExecution();
        tearDownTestRunner(testParameters, coreScript);
    }
}
